language: node_js

# Use stable version of Node.js
node_js:
  - node

# Cache installed node_modules between builds
cache:
  directories:
    - node_modules

# Set up build dependencies
install:
  - yarn install

# Compile the Gatsby site
script:
  - yarn build

# Deploy by pushing to GitHub Pages
deploy:
  # Opt in to Travis' Deployment V2
  edge: true
  provider: pages:git
  token: $GITHUB_TOKEN
  target-branch: gh-pages
  local_dir: public
  keep_history: false
  # Skip deploys from branches other than `master`
  on:
    branch: master